# Generated by Django 4.1.2 on 2022-10-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='name2',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='name1',
            new_name='Artiste',
        ),
    ]
