# Generated by Django 4.1.2 on 2022-10-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_name2_lyric_song_rename_name1_song_artiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
